version: 1
newItemTransaction:
  url: http://localhost:8090/new/item_transaction
newGunStat:
  url: http://localhost:8090/new/gun_stat
events:
  hostname: kafka
  port: 9092
  topic: events
event_logs:
  hostname: kafka
  port: 9092
  topic: event_log
app:
  host: 0.0.0.0
  port: 8080