# Lab 8

stages:
  - build
  - lint
  - test
  - zip

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - venv/bin/pip3 install -r requirements.txt

build:
  stage: build
  tags:
    - lab8
  script:
    - echo "Build Stage - Setup the virtual environment and install dependencies"

lint:
  stage: lint
  tags:
    - lab8
  script:
    - pylint --fail-under 5 *.py

test_and_coverage:
  stage: test
  tags:
    - lab8
  script:
    - source venv/bin/activate
    - rm -f coverage.xml
    - |
      for file in $(find . -type f -name "test*.py" ! -path "./venv/*"); do
        echo "Running: $file"
        python -m coverage run $file  
      done
    - coverage report
  artifacts:
    paths:
      - coverage.xml
    reports:
      junit: 
        - test-reports/*.xml
        - api-test-reports/*.xml

zip:
  stage: zip
  tags: 
    - lab8
  script:
    - zip -r app.zip *.py
  artifacts:
    paths:
      - app.zip

