version: 1
datastore:
  filename: /data/event_logs.sqlite
scheduler:
  period_sec: 5
eventstore:
  url: http://localhost:8090
events:
  hostname: kafka
  port: 9092
  topic: event_log
app:
  host: 0.0.0.0
  port: 8120