version: 1
datastore:
  filename: /data/stats.sqlite
scheduler:
  period_sec: 5
eventstore:
  url: http://35.230.127.229/storage
mysql:
  url: db
  port: 3306
  user: "sora"
  password: "sora"
  db: events
events:
  hostname: kafka
  port: 9092
  topic: event_log
  threshold: 25
app:
  host: 0.0.0.0
  port: 8100
request:
  timeout: 10