---
openapi: 3.1.0
info:
  title: Player Stats API
  description: This API receives each player's gun stats and item purchase history.
  contact:
    email: sschlegel1@my.bcit.ca
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
tags:
- name: event_logger
  description: Stores event logs
paths:
  /get/event_stats:
    get:
      tags: 
      - event_logger
      summary: fetches the event stats
      description: "Checks the database for the current count of each log even received"
      operationId: app.fetch_event_stats
      responses:
        '200':
          description: Successfully returned a list of gun stats
          content: 
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/EventStats'
        '400':
          description: Invalid request
          content: 
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    EventsStats:
      required:
      - "0001"
      - "0002"
      - "0003"
      - "0004"
      type: object
      properties:
        "0001":
          type: integer
          example: 10
        "0002":
          type: integer
          example: 22
        "0003":
          type: integer
          example: 8
        "0004":
          type: integer
          example: 51