version: 1
datastore:
  user: "sora"
  password: "sora"
  hostname: db
  port: 3306
  db: events
events:
  hostname: kafka
  port: 9092
  topic: events
event_logs:
  hostname: kafka
  port: 9092
  topic: event_log
